
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PriceTier` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PriceTier
 * 
 */
export type PriceTierModel = runtime.Types.Result.DefaultSelection<Prisma.$PriceTierPayload>

export type AggregatePriceTier = {
  _count: PriceTierCountAggregateOutputType | null
  _avg: PriceTierAvgAggregateOutputType | null
  _sum: PriceTierSumAggregateOutputType | null
  _min: PriceTierMinAggregateOutputType | null
  _max: PriceTierMaxAggregateOutputType | null
}

export type PriceTierAvgAggregateOutputType = {
  minQty: number | null
  maxQty: number | null
  price: number | null
}

export type PriceTierSumAggregateOutputType = {
  minQty: number | null
  maxQty: number | null
  price: number | null
}

export type PriceTierMinAggregateOutputType = {
  id: string | null
  productId: string | null
  minQty: number | null
  maxQty: number | null
  price: number | null
  type: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PriceTierMaxAggregateOutputType = {
  id: string | null
  productId: string | null
  minQty: number | null
  maxQty: number | null
  price: number | null
  type: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PriceTierCountAggregateOutputType = {
  id: number
  productId: number
  minQty: number
  maxQty: number
  price: number
  type: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PriceTierAvgAggregateInputType = {
  minQty?: true
  maxQty?: true
  price?: true
}

export type PriceTierSumAggregateInputType = {
  minQty?: true
  maxQty?: true
  price?: true
}

export type PriceTierMinAggregateInputType = {
  id?: true
  productId?: true
  minQty?: true
  maxQty?: true
  price?: true
  type?: true
  createdAt?: true
  updatedAt?: true
}

export type PriceTierMaxAggregateInputType = {
  id?: true
  productId?: true
  minQty?: true
  maxQty?: true
  price?: true
  type?: true
  createdAt?: true
  updatedAt?: true
}

export type PriceTierCountAggregateInputType = {
  id?: true
  productId?: true
  minQty?: true
  maxQty?: true
  price?: true
  type?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PriceTierAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PriceTier to aggregate.
   */
  where?: Prisma.PriceTierWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceTiers to fetch.
   */
  orderBy?: Prisma.PriceTierOrderByWithRelationInput | Prisma.PriceTierOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PriceTierWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceTiers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceTiers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PriceTiers
  **/
  _count?: true | PriceTierCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PriceTierAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PriceTierSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PriceTierMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PriceTierMaxAggregateInputType
}

export type GetPriceTierAggregateType<T extends PriceTierAggregateArgs> = {
      [P in keyof T & keyof AggregatePriceTier]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePriceTier[P]>
    : Prisma.GetScalarType<T[P], AggregatePriceTier[P]>
}




export type PriceTierGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PriceTierWhereInput
  orderBy?: Prisma.PriceTierOrderByWithAggregationInput | Prisma.PriceTierOrderByWithAggregationInput[]
  by: Prisma.PriceTierScalarFieldEnum[] | Prisma.PriceTierScalarFieldEnum
  having?: Prisma.PriceTierScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PriceTierCountAggregateInputType | true
  _avg?: PriceTierAvgAggregateInputType
  _sum?: PriceTierSumAggregateInputType
  _min?: PriceTierMinAggregateInputType
  _max?: PriceTierMaxAggregateInputType
}

export type PriceTierGroupByOutputType = {
  id: string
  productId: string
  minQty: number
  maxQty: number
  price: number
  type: string
  createdAt: Date
  updatedAt: Date
  _count: PriceTierCountAggregateOutputType | null
  _avg: PriceTierAvgAggregateOutputType | null
  _sum: PriceTierSumAggregateOutputType | null
  _min: PriceTierMinAggregateOutputType | null
  _max: PriceTierMaxAggregateOutputType | null
}

type GetPriceTierGroupByPayload<T extends PriceTierGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PriceTierGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PriceTierGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PriceTierGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PriceTierGroupByOutputType[P]>
      }
    >
  >



export type PriceTierWhereInput = {
  AND?: Prisma.PriceTierWhereInput | Prisma.PriceTierWhereInput[]
  OR?: Prisma.PriceTierWhereInput[]
  NOT?: Prisma.PriceTierWhereInput | Prisma.PriceTierWhereInput[]
  id?: Prisma.StringFilter<"PriceTier"> | string
  productId?: Prisma.StringFilter<"PriceTier"> | string
  minQty?: Prisma.IntFilter<"PriceTier"> | number
  maxQty?: Prisma.IntFilter<"PriceTier"> | number
  price?: Prisma.FloatFilter<"PriceTier"> | number
  type?: Prisma.StringFilter<"PriceTier"> | string
  createdAt?: Prisma.DateTimeFilter<"PriceTier"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PriceTier"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type PriceTierOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  minQty?: Prisma.SortOrder
  maxQty?: Prisma.SortOrder
  price?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
}

export type PriceTierWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PriceTierWhereInput | Prisma.PriceTierWhereInput[]
  OR?: Prisma.PriceTierWhereInput[]
  NOT?: Prisma.PriceTierWhereInput | Prisma.PriceTierWhereInput[]
  productId?: Prisma.StringFilter<"PriceTier"> | string
  minQty?: Prisma.IntFilter<"PriceTier"> | number
  maxQty?: Prisma.IntFilter<"PriceTier"> | number
  price?: Prisma.FloatFilter<"PriceTier"> | number
  type?: Prisma.StringFilter<"PriceTier"> | string
  createdAt?: Prisma.DateTimeFilter<"PriceTier"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PriceTier"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id">

export type PriceTierOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  minQty?: Prisma.SortOrder
  maxQty?: Prisma.SortOrder
  price?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PriceTierCountOrderByAggregateInput
  _avg?: Prisma.PriceTierAvgOrderByAggregateInput
  _max?: Prisma.PriceTierMaxOrderByAggregateInput
  _min?: Prisma.PriceTierMinOrderByAggregateInput
  _sum?: Prisma.PriceTierSumOrderByAggregateInput
}

export type PriceTierScalarWhereWithAggregatesInput = {
  AND?: Prisma.PriceTierScalarWhereWithAggregatesInput | Prisma.PriceTierScalarWhereWithAggregatesInput[]
  OR?: Prisma.PriceTierScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PriceTierScalarWhereWithAggregatesInput | Prisma.PriceTierScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PriceTier"> | string
  productId?: Prisma.StringWithAggregatesFilter<"PriceTier"> | string
  minQty?: Prisma.IntWithAggregatesFilter<"PriceTier"> | number
  maxQty?: Prisma.IntWithAggregatesFilter<"PriceTier"> | number
  price?: Prisma.FloatWithAggregatesFilter<"PriceTier"> | number
  type?: Prisma.StringWithAggregatesFilter<"PriceTier"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PriceTier"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PriceTier"> | Date | string
}

export type PriceTierCreateInput = {
  id?: string
  minQty: number
  maxQty: number
  price: number
  type?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutPriceTiersInput
}

export type PriceTierUncheckedCreateInput = {
  id?: string
  productId: string
  minQty: number
  maxQty: number
  price: number
  type?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PriceTierUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  minQty?: Prisma.IntFieldUpdateOperationsInput | number
  maxQty?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutPriceTiersNestedInput
}

export type PriceTierUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  minQty?: Prisma.IntFieldUpdateOperationsInput | number
  maxQty?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceTierCreateManyInput = {
  id?: string
  productId: string
  minQty: number
  maxQty: number
  price: number
  type?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PriceTierUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  minQty?: Prisma.IntFieldUpdateOperationsInput | number
  maxQty?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceTierUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  minQty?: Prisma.IntFieldUpdateOperationsInput | number
  maxQty?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceTierListRelationFilter = {
  every?: Prisma.PriceTierWhereInput
  some?: Prisma.PriceTierWhereInput
  none?: Prisma.PriceTierWhereInput
}

export type PriceTierOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PriceTierCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  minQty?: Prisma.SortOrder
  maxQty?: Prisma.SortOrder
  price?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PriceTierAvgOrderByAggregateInput = {
  minQty?: Prisma.SortOrder
  maxQty?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type PriceTierMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  minQty?: Prisma.SortOrder
  maxQty?: Prisma.SortOrder
  price?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PriceTierMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  minQty?: Prisma.SortOrder
  maxQty?: Prisma.SortOrder
  price?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PriceTierSumOrderByAggregateInput = {
  minQty?: Prisma.SortOrder
  maxQty?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type PriceTierCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.PriceTierCreateWithoutProductInput, Prisma.PriceTierUncheckedCreateWithoutProductInput> | Prisma.PriceTierCreateWithoutProductInput[] | Prisma.PriceTierUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.PriceTierCreateOrConnectWithoutProductInput | Prisma.PriceTierCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.PriceTierCreateManyProductInputEnvelope
  connect?: Prisma.PriceTierWhereUniqueInput | Prisma.PriceTierWhereUniqueInput[]
}

export type PriceTierUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.PriceTierCreateWithoutProductInput, Prisma.PriceTierUncheckedCreateWithoutProductInput> | Prisma.PriceTierCreateWithoutProductInput[] | Prisma.PriceTierUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.PriceTierCreateOrConnectWithoutProductInput | Prisma.PriceTierCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.PriceTierCreateManyProductInputEnvelope
  connect?: Prisma.PriceTierWhereUniqueInput | Prisma.PriceTierWhereUniqueInput[]
}

export type PriceTierUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.PriceTierCreateWithoutProductInput, Prisma.PriceTierUncheckedCreateWithoutProductInput> | Prisma.PriceTierCreateWithoutProductInput[] | Prisma.PriceTierUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.PriceTierCreateOrConnectWithoutProductInput | Prisma.PriceTierCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.PriceTierUpsertWithWhereUniqueWithoutProductInput | Prisma.PriceTierUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.PriceTierCreateManyProductInputEnvelope
  set?: Prisma.PriceTierWhereUniqueInput | Prisma.PriceTierWhereUniqueInput[]
  disconnect?: Prisma.PriceTierWhereUniqueInput | Prisma.PriceTierWhereUniqueInput[]
  delete?: Prisma.PriceTierWhereUniqueInput | Prisma.PriceTierWhereUniqueInput[]
  connect?: Prisma.PriceTierWhereUniqueInput | Prisma.PriceTierWhereUniqueInput[]
  update?: Prisma.PriceTierUpdateWithWhereUniqueWithoutProductInput | Prisma.PriceTierUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.PriceTierUpdateManyWithWhereWithoutProductInput | Prisma.PriceTierUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.PriceTierScalarWhereInput | Prisma.PriceTierScalarWhereInput[]
}

export type PriceTierUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.PriceTierCreateWithoutProductInput, Prisma.PriceTierUncheckedCreateWithoutProductInput> | Prisma.PriceTierCreateWithoutProductInput[] | Prisma.PriceTierUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.PriceTierCreateOrConnectWithoutProductInput | Prisma.PriceTierCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.PriceTierUpsertWithWhereUniqueWithoutProductInput | Prisma.PriceTierUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.PriceTierCreateManyProductInputEnvelope
  set?: Prisma.PriceTierWhereUniqueInput | Prisma.PriceTierWhereUniqueInput[]
  disconnect?: Prisma.PriceTierWhereUniqueInput | Prisma.PriceTierWhereUniqueInput[]
  delete?: Prisma.PriceTierWhereUniqueInput | Prisma.PriceTierWhereUniqueInput[]
  connect?: Prisma.PriceTierWhereUniqueInput | Prisma.PriceTierWhereUniqueInput[]
  update?: Prisma.PriceTierUpdateWithWhereUniqueWithoutProductInput | Prisma.PriceTierUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.PriceTierUpdateManyWithWhereWithoutProductInput | Prisma.PriceTierUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.PriceTierScalarWhereInput | Prisma.PriceTierScalarWhereInput[]
}

export type PriceTierCreateWithoutProductInput = {
  id?: string
  minQty: number
  maxQty: number
  price: number
  type?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PriceTierUncheckedCreateWithoutProductInput = {
  id?: string
  minQty: number
  maxQty: number
  price: number
  type?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PriceTierCreateOrConnectWithoutProductInput = {
  where: Prisma.PriceTierWhereUniqueInput
  create: Prisma.XOR<Prisma.PriceTierCreateWithoutProductInput, Prisma.PriceTierUncheckedCreateWithoutProductInput>
}

export type PriceTierCreateManyProductInputEnvelope = {
  data: Prisma.PriceTierCreateManyProductInput | Prisma.PriceTierCreateManyProductInput[]
}

export type PriceTierUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.PriceTierWhereUniqueInput
  update: Prisma.XOR<Prisma.PriceTierUpdateWithoutProductInput, Prisma.PriceTierUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.PriceTierCreateWithoutProductInput, Prisma.PriceTierUncheckedCreateWithoutProductInput>
}

export type PriceTierUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.PriceTierWhereUniqueInput
  data: Prisma.XOR<Prisma.PriceTierUpdateWithoutProductInput, Prisma.PriceTierUncheckedUpdateWithoutProductInput>
}

export type PriceTierUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.PriceTierScalarWhereInput
  data: Prisma.XOR<Prisma.PriceTierUpdateManyMutationInput, Prisma.PriceTierUncheckedUpdateManyWithoutProductInput>
}

export type PriceTierScalarWhereInput = {
  AND?: Prisma.PriceTierScalarWhereInput | Prisma.PriceTierScalarWhereInput[]
  OR?: Prisma.PriceTierScalarWhereInput[]
  NOT?: Prisma.PriceTierScalarWhereInput | Prisma.PriceTierScalarWhereInput[]
  id?: Prisma.StringFilter<"PriceTier"> | string
  productId?: Prisma.StringFilter<"PriceTier"> | string
  minQty?: Prisma.IntFilter<"PriceTier"> | number
  maxQty?: Prisma.IntFilter<"PriceTier"> | number
  price?: Prisma.FloatFilter<"PriceTier"> | number
  type?: Prisma.StringFilter<"PriceTier"> | string
  createdAt?: Prisma.DateTimeFilter<"PriceTier"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PriceTier"> | Date | string
}

export type PriceTierCreateManyProductInput = {
  id?: string
  minQty: number
  maxQty: number
  price: number
  type?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PriceTierUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  minQty?: Prisma.IntFieldUpdateOperationsInput | number
  maxQty?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceTierUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  minQty?: Prisma.IntFieldUpdateOperationsInput | number
  maxQty?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceTierUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  minQty?: Prisma.IntFieldUpdateOperationsInput | number
  maxQty?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PriceTierSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  minQty?: boolean
  maxQty?: boolean
  price?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["priceTier"]>

export type PriceTierSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  minQty?: boolean
  maxQty?: boolean
  price?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["priceTier"]>

export type PriceTierSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  minQty?: boolean
  maxQty?: boolean
  price?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["priceTier"]>

export type PriceTierSelectScalar = {
  id?: boolean
  productId?: boolean
  minQty?: boolean
  maxQty?: boolean
  price?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PriceTierOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productId" | "minQty" | "maxQty" | "price" | "type" | "createdAt" | "updatedAt", ExtArgs["result"]["priceTier"]>
export type PriceTierInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type PriceTierIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type PriceTierIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $PriceTierPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PriceTier"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    productId: string
    minQty: number
    maxQty: number
    price: number
    type: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["priceTier"]>
  composites: {}
}

export type PriceTierGetPayload<S extends boolean | null | undefined | PriceTierDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PriceTierPayload, S>

export type PriceTierCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PriceTierFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PriceTierCountAggregateInputType | true
  }

export interface PriceTierDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PriceTier'], meta: { name: 'PriceTier' } }
  /**
   * Find zero or one PriceTier that matches the filter.
   * @param {PriceTierFindUniqueArgs} args - Arguments to find a PriceTier
   * @example
   * // Get one PriceTier
   * const priceTier = await prisma.priceTier.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PriceTierFindUniqueArgs>(args: Prisma.SelectSubset<T, PriceTierFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PriceTierClient<runtime.Types.Result.GetResult<Prisma.$PriceTierPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PriceTier that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PriceTierFindUniqueOrThrowArgs} args - Arguments to find a PriceTier
   * @example
   * // Get one PriceTier
   * const priceTier = await prisma.priceTier.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PriceTierFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PriceTierFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PriceTierClient<runtime.Types.Result.GetResult<Prisma.$PriceTierPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PriceTier that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceTierFindFirstArgs} args - Arguments to find a PriceTier
   * @example
   * // Get one PriceTier
   * const priceTier = await prisma.priceTier.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PriceTierFindFirstArgs>(args?: Prisma.SelectSubset<T, PriceTierFindFirstArgs<ExtArgs>>): Prisma.Prisma__PriceTierClient<runtime.Types.Result.GetResult<Prisma.$PriceTierPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PriceTier that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceTierFindFirstOrThrowArgs} args - Arguments to find a PriceTier
   * @example
   * // Get one PriceTier
   * const priceTier = await prisma.priceTier.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PriceTierFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PriceTierFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PriceTierClient<runtime.Types.Result.GetResult<Prisma.$PriceTierPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PriceTiers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceTierFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PriceTiers
   * const priceTiers = await prisma.priceTier.findMany()
   * 
   * // Get first 10 PriceTiers
   * const priceTiers = await prisma.priceTier.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const priceTierWithIdOnly = await prisma.priceTier.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PriceTierFindManyArgs>(args?: Prisma.SelectSubset<T, PriceTierFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceTierPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PriceTier.
   * @param {PriceTierCreateArgs} args - Arguments to create a PriceTier.
   * @example
   * // Create one PriceTier
   * const PriceTier = await prisma.priceTier.create({
   *   data: {
   *     // ... data to create a PriceTier
   *   }
   * })
   * 
   */
  create<T extends PriceTierCreateArgs>(args: Prisma.SelectSubset<T, PriceTierCreateArgs<ExtArgs>>): Prisma.Prisma__PriceTierClient<runtime.Types.Result.GetResult<Prisma.$PriceTierPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PriceTiers.
   * @param {PriceTierCreateManyArgs} args - Arguments to create many PriceTiers.
   * @example
   * // Create many PriceTiers
   * const priceTier = await prisma.priceTier.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PriceTierCreateManyArgs>(args?: Prisma.SelectSubset<T, PriceTierCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PriceTiers and returns the data saved in the database.
   * @param {PriceTierCreateManyAndReturnArgs} args - Arguments to create many PriceTiers.
   * @example
   * // Create many PriceTiers
   * const priceTier = await prisma.priceTier.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PriceTiers and only return the `id`
   * const priceTierWithIdOnly = await prisma.priceTier.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PriceTierCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PriceTierCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceTierPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PriceTier.
   * @param {PriceTierDeleteArgs} args - Arguments to delete one PriceTier.
   * @example
   * // Delete one PriceTier
   * const PriceTier = await prisma.priceTier.delete({
   *   where: {
   *     // ... filter to delete one PriceTier
   *   }
   * })
   * 
   */
  delete<T extends PriceTierDeleteArgs>(args: Prisma.SelectSubset<T, PriceTierDeleteArgs<ExtArgs>>): Prisma.Prisma__PriceTierClient<runtime.Types.Result.GetResult<Prisma.$PriceTierPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PriceTier.
   * @param {PriceTierUpdateArgs} args - Arguments to update one PriceTier.
   * @example
   * // Update one PriceTier
   * const priceTier = await prisma.priceTier.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PriceTierUpdateArgs>(args: Prisma.SelectSubset<T, PriceTierUpdateArgs<ExtArgs>>): Prisma.Prisma__PriceTierClient<runtime.Types.Result.GetResult<Prisma.$PriceTierPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PriceTiers.
   * @param {PriceTierDeleteManyArgs} args - Arguments to filter PriceTiers to delete.
   * @example
   * // Delete a few PriceTiers
   * const { count } = await prisma.priceTier.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PriceTierDeleteManyArgs>(args?: Prisma.SelectSubset<T, PriceTierDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PriceTiers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceTierUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PriceTiers
   * const priceTier = await prisma.priceTier.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PriceTierUpdateManyArgs>(args: Prisma.SelectSubset<T, PriceTierUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PriceTiers and returns the data updated in the database.
   * @param {PriceTierUpdateManyAndReturnArgs} args - Arguments to update many PriceTiers.
   * @example
   * // Update many PriceTiers
   * const priceTier = await prisma.priceTier.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PriceTiers and only return the `id`
   * const priceTierWithIdOnly = await prisma.priceTier.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PriceTierUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PriceTierUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceTierPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PriceTier.
   * @param {PriceTierUpsertArgs} args - Arguments to update or create a PriceTier.
   * @example
   * // Update or create a PriceTier
   * const priceTier = await prisma.priceTier.upsert({
   *   create: {
   *     // ... data to create a PriceTier
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PriceTier we want to update
   *   }
   * })
   */
  upsert<T extends PriceTierUpsertArgs>(args: Prisma.SelectSubset<T, PriceTierUpsertArgs<ExtArgs>>): Prisma.Prisma__PriceTierClient<runtime.Types.Result.GetResult<Prisma.$PriceTierPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PriceTiers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceTierCountArgs} args - Arguments to filter PriceTiers to count.
   * @example
   * // Count the number of PriceTiers
   * const count = await prisma.priceTier.count({
   *   where: {
   *     // ... the filter for the PriceTiers we want to count
   *   }
   * })
  **/
  count<T extends PriceTierCountArgs>(
    args?: Prisma.Subset<T, PriceTierCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PriceTierCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PriceTier.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceTierAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PriceTierAggregateArgs>(args: Prisma.Subset<T, PriceTierAggregateArgs>): Prisma.PrismaPromise<GetPriceTierAggregateType<T>>

  /**
   * Group by PriceTier.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceTierGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PriceTierGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PriceTierGroupByArgs['orderBy'] }
      : { orderBy?: PriceTierGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PriceTierGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPriceTierGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PriceTier model
 */
readonly fields: PriceTierFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PriceTier.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PriceTierClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PriceTier model
 */
export interface PriceTierFieldRefs {
  readonly id: Prisma.FieldRef<"PriceTier", 'String'>
  readonly productId: Prisma.FieldRef<"PriceTier", 'String'>
  readonly minQty: Prisma.FieldRef<"PriceTier", 'Int'>
  readonly maxQty: Prisma.FieldRef<"PriceTier", 'Int'>
  readonly price: Prisma.FieldRef<"PriceTier", 'Float'>
  readonly type: Prisma.FieldRef<"PriceTier", 'String'>
  readonly createdAt: Prisma.FieldRef<"PriceTier", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PriceTier", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PriceTier findUnique
 */
export type PriceTierFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierInclude<ExtArgs> | null
  /**
   * Filter, which PriceTier to fetch.
   */
  where: Prisma.PriceTierWhereUniqueInput
}

/**
 * PriceTier findUniqueOrThrow
 */
export type PriceTierFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierInclude<ExtArgs> | null
  /**
   * Filter, which PriceTier to fetch.
   */
  where: Prisma.PriceTierWhereUniqueInput
}

/**
 * PriceTier findFirst
 */
export type PriceTierFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierInclude<ExtArgs> | null
  /**
   * Filter, which PriceTier to fetch.
   */
  where?: Prisma.PriceTierWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceTiers to fetch.
   */
  orderBy?: Prisma.PriceTierOrderByWithRelationInput | Prisma.PriceTierOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PriceTiers.
   */
  cursor?: Prisma.PriceTierWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceTiers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceTiers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PriceTiers.
   */
  distinct?: Prisma.PriceTierScalarFieldEnum | Prisma.PriceTierScalarFieldEnum[]
}

/**
 * PriceTier findFirstOrThrow
 */
export type PriceTierFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierInclude<ExtArgs> | null
  /**
   * Filter, which PriceTier to fetch.
   */
  where?: Prisma.PriceTierWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceTiers to fetch.
   */
  orderBy?: Prisma.PriceTierOrderByWithRelationInput | Prisma.PriceTierOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PriceTiers.
   */
  cursor?: Prisma.PriceTierWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceTiers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceTiers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PriceTiers.
   */
  distinct?: Prisma.PriceTierScalarFieldEnum | Prisma.PriceTierScalarFieldEnum[]
}

/**
 * PriceTier findMany
 */
export type PriceTierFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierInclude<ExtArgs> | null
  /**
   * Filter, which PriceTiers to fetch.
   */
  where?: Prisma.PriceTierWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceTiers to fetch.
   */
  orderBy?: Prisma.PriceTierOrderByWithRelationInput | Prisma.PriceTierOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PriceTiers.
   */
  cursor?: Prisma.PriceTierWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceTiers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceTiers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PriceTiers.
   */
  distinct?: Prisma.PriceTierScalarFieldEnum | Prisma.PriceTierScalarFieldEnum[]
}

/**
 * PriceTier create
 */
export type PriceTierCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierInclude<ExtArgs> | null
  /**
   * The data needed to create a PriceTier.
   */
  data: Prisma.XOR<Prisma.PriceTierCreateInput, Prisma.PriceTierUncheckedCreateInput>
}

/**
 * PriceTier createMany
 */
export type PriceTierCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PriceTiers.
   */
  data: Prisma.PriceTierCreateManyInput | Prisma.PriceTierCreateManyInput[]
}

/**
 * PriceTier createManyAndReturn
 */
export type PriceTierCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * The data used to create many PriceTiers.
   */
  data: Prisma.PriceTierCreateManyInput | Prisma.PriceTierCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PriceTier update
 */
export type PriceTierUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierInclude<ExtArgs> | null
  /**
   * The data needed to update a PriceTier.
   */
  data: Prisma.XOR<Prisma.PriceTierUpdateInput, Prisma.PriceTierUncheckedUpdateInput>
  /**
   * Choose, which PriceTier to update.
   */
  where: Prisma.PriceTierWhereUniqueInput
}

/**
 * PriceTier updateMany
 */
export type PriceTierUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PriceTiers.
   */
  data: Prisma.XOR<Prisma.PriceTierUpdateManyMutationInput, Prisma.PriceTierUncheckedUpdateManyInput>
  /**
   * Filter which PriceTiers to update
   */
  where?: Prisma.PriceTierWhereInput
  /**
   * Limit how many PriceTiers to update.
   */
  limit?: number
}

/**
 * PriceTier updateManyAndReturn
 */
export type PriceTierUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * The data used to update PriceTiers.
   */
  data: Prisma.XOR<Prisma.PriceTierUpdateManyMutationInput, Prisma.PriceTierUncheckedUpdateManyInput>
  /**
   * Filter which PriceTiers to update
   */
  where?: Prisma.PriceTierWhereInput
  /**
   * Limit how many PriceTiers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PriceTier upsert
 */
export type PriceTierUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierInclude<ExtArgs> | null
  /**
   * The filter to search for the PriceTier to update in case it exists.
   */
  where: Prisma.PriceTierWhereUniqueInput
  /**
   * In case the PriceTier found by the `where` argument doesn't exist, create a new PriceTier with this data.
   */
  create: Prisma.XOR<Prisma.PriceTierCreateInput, Prisma.PriceTierUncheckedCreateInput>
  /**
   * In case the PriceTier was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PriceTierUpdateInput, Prisma.PriceTierUncheckedUpdateInput>
}

/**
 * PriceTier delete
 */
export type PriceTierDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierInclude<ExtArgs> | null
  /**
   * Filter which PriceTier to delete.
   */
  where: Prisma.PriceTierWhereUniqueInput
}

/**
 * PriceTier deleteMany
 */
export type PriceTierDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PriceTiers to delete
   */
  where?: Prisma.PriceTierWhereInput
  /**
   * Limit how many PriceTiers to delete.
   */
  limit?: number
}

/**
 * PriceTier without action
 */
export type PriceTierDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierInclude<ExtArgs> | null
}
