
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Address
 * 
 */
export type Address = Prisma.AddressModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Brand
 * 
 */
export type Brand = Prisma.BrandModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model ProductVariant
 * 
 */
export type ProductVariant = Prisma.ProductVariantModel
/**
 * Model ProductImage
 * 
 */
export type ProductImage = Prisma.ProductImageModel
/**
 * Model PriceTier
 * 
 */
export type PriceTier = Prisma.PriceTierModel
/**
 * Model Cart
 * 
 */
export type Cart = Prisma.CartModel
/**
 * Model CartItem
 * 
 */
export type CartItem = Prisma.CartItemModel
/**
 * Model Order
 * 
 */
export type Order = Prisma.OrderModel
/**
 * Model OrderItem
 * 
 */
export type OrderItem = Prisma.OrderItemModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model Shipment
 * 
 */
export type Shipment = Prisma.ShipmentModel
/**
 * Model WholesaleApplication
 * 
 */
export type WholesaleApplication = Prisma.WholesaleApplicationModel
/**
 * Model Quote
 * 
 */
export type Quote = Prisma.QuoteModel
/**
 * Model QuoteItem
 * 
 */
export type QuoteItem = Prisma.QuoteItemModel
/**
 * Model Discount
 * 
 */
export type Discount = Prisma.DiscountModel
/**
 * Model Review
 * 
 */
export type Review = Prisma.ReviewModel
/**
 * Model Wishlist
 * 
 */
export type Wishlist = Prisma.WishlistModel
/**
 * Model WishlistItem
 * 
 */
export type WishlistItem = Prisma.WishlistItemModel
/**
 * Model Banner
 * 
 */
export type Banner = Prisma.BannerModel
/**
 * Model Setting
 * 
 */
export type Setting = Prisma.SettingModel
/**
 * Model AdminAuditLog
 * 
 */
export type AdminAuditLog = Prisma.AdminAuditLogModel
