
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  GUEST: 'GUEST',
  CUSTOMER: 'CUSTOMER',
  WHOLESALE: 'WHOLESALE',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const AccountType = {
  RETAIL: 'RETAIL',
  WHOLESALE: 'WHOLESALE',
  HYBRID: 'HYBRID'
} as const

export type AccountType = (typeof AccountType)[keyof typeof AccountType]


export const WholesaleStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
} as const

export type WholesaleStatus = (typeof WholesaleStatus)[keyof typeof WholesaleStatus]


export const OrderType = {
  RETAIL: 'RETAIL',
  WHOLESALE: 'WHOLESALE',
  QUOTE_CONVERTED: 'QUOTE_CONVERTED'
} as const

export type OrderType = (typeof OrderType)[keyof typeof OrderType]


export const PaymentStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]


export const OrderStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]


export const FulfillmentStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
} as const

export type FulfillmentStatus = (typeof FulfillmentStatus)[keyof typeof FulfillmentStatus]


export const QuoteStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  REVIEWING: 'REVIEWING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CONVERTED_TO_ORDER: 'CONVERTED_TO_ORDER'
} as const

export type QuoteStatus = (typeof QuoteStatus)[keyof typeof QuoteStatus]
